name: Re-Update Markdown Performance
on:
  push:
    paths:
      - "**.py"
jobs:
  update_existing_performance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Get List of Already-Filled Markdown Files
        id: getfile
        run: |-
          echo "" > already_filled_files.txt
          changed_files=$(git diff --name-only --diff-filter=M origin/main HEAD)

          echo "newly changed files: $changed_files"

          while IFS= read -r file; do
                if [[ "$file" == *.py ]]; then
                      dir=$(dirname "$file")
                      readme_path="$dir/README.md"
                      if [[ -f "$readme_path" ]]; then
                        echo "./$file" >> already_filled_files.txt
                      fi
                fi
          done <<< "$changed_files"

          cat ./already_filled_files.txt
      - name: Update Performance in Markdown
        uses: dltkdgns00/BOJ-action@main
        with:
          path: already_filled_files.txt
          user_id: ydh9516
          language_id: 1003
      - name: remove already_filled_files.txt
        run: rm already_filled_files.txt
      - name: Commit and push changes
        run: >-
          git config --local user.email
          "github-actions[bot]@users.noreply.github.com"

          git config --local user.name "github-actions[bot]"

          git add .

          git status

          if [[ -n "$(git status --porcelain)" ]]; then
          	git commit -m "Re-Update performance details"
          	git push
          else
          	echo "No changes to commit."
          fi
